// import { Inter } from 'next/font/google'
import Head from 'next/head'
import { useState } from 'react'

import { ListSeries } from 'src/components/ListSeries'
import { useGetSeries } from 'src/hooks/useGetSeries'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isEmptyList, setIsEmptyList] = useState<boolean>(false)
  const [selectedSeries, setSelectedSeries] = useState<string[]>([])

  const { data: series, isLoading } = useGetSeries({ onError: () => setIsEmptyList(true) })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full h-f flex items-center">
        {series ? (
          <ListSeries
            isLoading={isLoading}
            series={series.data}
            isEmpty={isEmptyList}
            setSeries={setSelectedSeries}
          />
        ) : (
          <div>error</div>
        )}
      </main>
    </>
  )
}
